pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            args '-v C:\ProgramData\Docker:c:\docker -e DOCKER_HOST=tcp://localhost:2375'
        }
    }
    environment {
        DOCKER_HOST = 'tcp://localhost:2375'
    }
    stages {
        stage('Test') {
            steps {
                bat 'node --version'
            }
        }
    }
}
